<?php

// Success responses
const RESPONSE_LOGIN_OK = 0;
const RESPONSE_REGISTRATION_OK = 1;
const RESPONSE_UPLOAD_OK = 2;
const RESPONSE_DOWNLOAD_OK = 3;
const RESPONSE_DB_SYNCHRONIZED = 4;
const RESPONSE_LOCAL_DB_OUT_OF_DATE = 5;
const RESPONSE_REMOTE_DB_OUT_OF_DATE = 6;
// Communication error responses
const RESPONSE_WRONG_PARAMETERS = -1;
const RESPONSE_WRONG_CREDENTIALS = -2;
// Server error responses
const RESPONSE_ERROR_UPLOADING_FILE = -3;
const RESPONSE_REMOTE_DB_NOT_FOUND = -4;
const RESPONSE_USERNAME_ALREADY_EXISTS = -5;
const RESPONSE_QUERY_ERROR = -6;
